name: Node.js CI

on:
  push:
    paths:
      - js/**
      - .github/workflows/js.yaml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - run: npm ci
      - run: npm test