name: Cargo Build & Test

on:
  push:
    paths:
      - rust/**
      - .github/workflows/rust.yaml

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: cargo test --verbose
        working-directory: ./rust
