name: Node.js CI

on:
  push:
    paths:
      - ts/**
      - .github/workflows/ts.yaml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Use Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: '20.10.0'
      - run: npm ci
        working-directory: ./ts
      - run: npm run test
        working-directory: ./ts
